<a href="https://colab.research.google.com/github/Kim-jong-hoon/week-2-3/blob/main/Numpy_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


NUMPY 배열 생성

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


0차원 배열

In [3]:
import numpy as np

arr = np.array(42)

print(arr)

42


1차원 배열

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


2차원 배열

In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


3차원 배열

In [6]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


차원의 개수 확인

In [7]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


다음 배열에서 첫번째 요소를 가져온다

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


다음 배열에서 세번째와 네번째 요소를 가져와 추가한다

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


첫번째 행, 두번째 열으 ㅣ요소에 접근한다

In [10]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


2번째 행 5번째 열의 요소 접근

In [11]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


첫 번째 배열의 두 번째 배열의 세 번째 요소에 접근합니다.

In [12]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


Numpy 배열 슬라이싱 / 1부터 5까지 요소를 슬라이스

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


4부터 슬라이스

In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


시작부터 4까지 요소 슬라이스

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])


[1 2 3 4]


빼기연산자를 사용하면 끝에서부터 인덱스 참조

In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


인덱스 1부터 5까지 다른 요소 반환

In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


다른 모든 배열 요소 반환

In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


두 번째 요소에서 인덱스 1부터 인덱스 4까지의 요소를 슬라이스합니다(포함되지 않음):

In [19]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


두 요소 모두에서 인덱스 2를 반환합니다.

In [20]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])


[3 8]


두 요소 모두에서 인덱스 1부터 인덱스 4까지(포함되지 않음) 슬라이스하면 2차원 배열이 반환됩니다.

In [21]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


NUMPY 데이터 유형 / 배열 객체의 데이터 유형을 가져옵니다.

In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


문자열을 포함하는 배열의 데이터 유형을 가져옵니다.

In [23]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


문자열 데이터 유형으로 배열을 만듭니다.

In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


4바이트 정수 데이터 유형을 갖는 배열을 생성합니다.

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


i'매개변수 값으로 다음을 사용하여 데이터 유형을 float에서 정수로 변경합니다 .

In [26]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


int매개변수 값으로 다음을 사용하여 데이터 유형을 float에서 정수로 변경합니다 .

In [28]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


정수형에서 부울형으로 데이터 유형을 변경합니다.

In [27]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


NUMPY 복사 대 뷰 / 복사본을 만들고, 원본 배열을 변경하고, 두 배열을 모두 표시합니다.

In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


뷰를 만들고, 원래 배열을 변경하고, 두 배열을 모두 표시합니다.

In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


뷰를 만들고, 뷰를 변경하고, 두 배열을 모두 표시합니다.

In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


NumPy 배열 모양 / 2차원 배열의 모양을 인쇄하세요.

In [32]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


ndmin값 1, 2, 3, 4를 갖는 벡터를 사용하여 5차원 배열을 만들고 마지막 차원의 값이 4인지 확인합니다.

In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


NumPy 배열 재구성 / 다음 12개 요소를 가진 1차원 배열을 2차원 배열로 변환하세요.가장 바깥쪽 차원에는 각각 3개의 요소가 있는 4개의 배열이 있습니다.



In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


다음의 12개 요소를 가진 1차원 배열을 3차원 배열로 변환하세요.
가장 바깥쪽 차원에는 각각 2개의 요소가 있는 3개의 배열을 포함하는 2개의 배열이 있습니다.

In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


반환된 배열이 복사본인지 뷰인지 확인하세요.

In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


8개의 요소를 가진 1차원 배열을 2x2개의 요소를 가진 3차원 배열로 변환:

In [37]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


배열을 1차원 배열로 변환합니다./배열을 평탄화한다는 것은 다차원 배열을 1차원 배열로 변환하는 것을 의미합니다.

우리는 reshape(-1)이것을 할 수 있습니다.

In [38]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


다음 1차원 배열의 요소를 반복합니다.

In [39]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


다음 2차원 배열의 요소를 반복합니다.

In [40]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


2차원 배열의 각 스칼라 요소를 반복합니다.

In [41]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


nditer()를 사용하여 배열 반복하기

In [42]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


배열을 문자열로 반복합니다.

In [43]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


2D 배열의 모든 스칼라 요소를 반복하면서 1개 요소를 건너뜁니다.

In [44]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


ndenumerate()를 사용한 열거형 반복

In [45]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


NumPy 배열 결합

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

행을 따라 두 개의 2차원 배열을 결합합니다(축=1):

In [46]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


스택 함수를 사용하여 배열 결합
스태킹은 연결과 동일하며, 유일한 차이점은 스태킹이 새로운 축을 따라 수행된다는 것입니다.

두 개의 1차원 배열을 두 번째 축을 따라 연결하면 배열을 서로 겹쳐 놓을 수 있습니다. 즉, 쌓기(stacking)라고 합니다.

메서드 에 조인할 배열 시퀀스를 stack()축과 함께 전달합니다. 축을 명시적으로 전달하지 않으면 0으로 간주됩니다.

In [47]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


행을 따라 쌓기
hstack() NumPy는 행을 따라 쌓는 도우미 함수를 제공합니다 .

In [48]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


열을 따라 쌓기
vstack()  NumPy는 열을 따라 쌓는 도우미 함수를 제공합니다 .

In [49]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


높이(깊이)에 따른 스태킹
NumPy는 높이를 따라 쌓는 도우미 함수를 제공하는데 dstack() , 이는 깊이와 같습니다.

In [51]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


NumPy 배열 분할/ 배열을 분할 할 array_split()때는 분할하려는 배열과 분할 횟수를 전달합니다.

In [52]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


배열을 4개 부분으로 나눕니다.

In [53]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


배열로 분할
이 메서드 의 반환 값 array_split()은 각 분할을 배열로 포함하는 배열입니다.

배열을 3개의 배열로 분할하면 모든 배열 요소와 마찬가지로 결과에서 해당 배열에 액세스할 수 있습니다.

In [54]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])


[1 2]
[3 4]
[5 6]


2차원 배열 분할
2차원 배열을 분할할 때도 동일한 구문을 사용합니다.

이 메서드를 사용하여 array_split()분할하려는 배열과 분할 횟수를 전달합니다.

In [55]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


2차원 배열을 3개의 2차원 배열로 분할합니다.

In [56]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


이 hsplit()방법을 사용하여 2차원 배열을 열을 따라 3개의 2차원 배열로 분할합니다.

In [57]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


배열 검색
배열에서 특정 값을 검색하고, 일치하는 값을 찾는 인덱스를 반환할 수 있습니다.

배열을 검색하려면 이 where()메서드를 사용하세요.

In [58]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


값이 짝수인 인덱스를 찾으세요.

In [59]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)
